In [1]:
import numpy as np

# Initialize population
def init_pop(pop_size):

    #Initializes the population with random solutions.
    #Each solution is a random configuration of queens (represented by integers 0-7).

    return np.random.randint(8, size=(pop_size, 8))  # Random positions for each queen

# Calculate fitness
def calc_fitness(population):

    #Calculates the fitness for each individual in the population.
    #Fitness is based on the number of conflicts (penalties) in a given solution.
    #The lower the penalty, the better the fitness.

    fitness_vals = []
    for x in population:
        penalty = 0
        for i in range(8):  # For each queen
            r = x[i]  # Row position of the queen
            for j in range(8):  # Compare with every other queen
                if i == j:
                    continue
                d = abs(i - j)  # Distance between queens in terms of rows
                if x[j] in [r, r - d, r + d]:  # Conflict if queens share the same column or diagonal
                    penalty += 1
        fitness_vals.append(-penalty)  # Lower penalty means better fitness
    return np.array(fitness_vals)

# Selection
def selection(population, fitness_vals):

    #Selects individuals based on their fitness using a probabilistic method.
    #Better individuals (with higher fitness) have a higher chance of being selected.

    probs = fitness_vals - fitness_vals.min() + 1  # Normalize probabilities to avoid negative values
    probs = probs / probs.sum()  # Normalize to make the sum of probabilities equal to 1
    N = len(population)
    indices = np.arange(N)
    selected_indices = np.random.choice(indices, size=N, p=probs)  # Select individuals based on their fitness probabilities
    return population[selected_indices]  # Return the selected individuals

# Crossover
def crossover(parent1, parent2, pc):

    #Performs crossover between two parents to create two children.
    #If random number is less than crossover probability (pc), crossover occurs.

    r = np.random.random()  # Random number to decide if crossover happens
    if r < pc:
        m = np.random.randint(1, 8)  # Random crossover point
        child1 = np.concatenate((parent1[:m], parent2[m:]))  # Child 1 inherits from both parents
        child2 = np.concatenate((parent2[:m], parent1[m:]))  # Child 2 inherits from both parents
    else:
        child1 = parent1.copy()  # No crossover, child1 is a copy of parent1
        child2 = parent2.copy()  # No crossover, child2 is a copy of parent2
    return child1, child2

# Mutation
def mutation(child, pm):

    #Mutates the child with a certain probability (pm).
    #A mutation randomly changes one queen's position.

    r = np.random.random()  # Random number to decide if mutation happens
    if r < pm:
        m = np.random.randint(8)  # Random position to mutate
        child[m] = np.random.randint(8)  # Assign a new random position for the mutated queen
    return child

# Crossover and mutation
def crossover_mutation(population, pc, pm):

    #Applies crossover and mutation to the entire population.
    #This creates a new population for the next generation.

    N = len(population)
    new_pop = np.empty((N, 8), dtype=int)  # New population array
    for i in range(0, N, 2):  # Process in pairs
        parent1 = population[i]
        parent2 = population[(i + 1) % N]  # Ensure pairing with wrap-around
        child1, child2 = crossover(parent1, parent2, pc)  # Apply crossover
        new_pop[i] = mutation(child1, pm)  # Apply mutation to child1
        if i + 1 < N:
            new_pop[i + 1] = mutation(child2, pm)  # Apply mutation to child2
    return new_pop

# Check if solution is found
def is_solution_found(population, fitness_vals):

    #Checks if any individual in the population has zero penalties (perfect solution).

    for i, fitness in enumerate(fitness_vals):
        if fitness == 0:  # If fitness is zero, the solution is found
            return True, population[i]  # Return the solution
    return False, None  # No solution found

# Genetic Algorithm
def genetic_algorithm(pop_size, pc, pm, max_generations):

    #The main genetic algorithm loop.
    #It repeatedly evolves the population until a solution is found or the max generations are reached.

    population = init_pop(pop_size)  # Initialize population
    for generation in range(max_generations):
        fitness_vals = calc_fitness(population)  # Calculate fitness for the population
        solution_found, solution = is_solution_found(population, fitness_vals)  # Check for solution
        if solution_found:
            print(f"Solution found in generation {generation}:")
            return solution  # Return the solution if found
        population = selection(population, fitness_vals)  # Select parents based on fitness
        population = crossover_mutation(population, pc, pm)  # Perform crossover and mutation
    print("No solution found within the maximum number of generations.")
    return None  # No solution after max generations

# Parameters
POP_SIZE = 100    # Number of individuals in the population
PC = 0.7          # Probability of crossover
PM = 0.1          # Probability of mutation
MAX_GENERATIONS = 100  # Maximum number of generations

# Run the Genetic Algorithm
solution = genetic_algorithm(POP_SIZE, PC, PM, MAX_GENERATIONS)

# Output the solution
if solution is not None:
    print("Solution:", solution)
else:
    print("No solution found.")


Solution found in generation 33:
Solution: [2 5 1 6 4 0 7 3]


In [3]:
import numpy as np

# Initialize population
def init_pop(pop_size):
    return np.random.randint(8, size=(pop_size, 8))

initial_population = init_pop(4)
print("Initial Population:")
print(initial_population)

# Calculate fitness
def calc_fitness(population):
    fitness_vals = []
    for x in population:
        penalty = 0
        for i in range(8):
            r = x[i]
            for j in range(8):
                if i == j:
                    continue
                d = abs(i - j)
                # Check for conflicts
                if x[j] in [r, r - d, r + d]:
                    penalty += 1
        # Higher fitness corresponds to fewer penalties
        fitness_vals.append(-penalty)
    return np.array(fitness_vals)

fitness_vals = calc_fitness(initial_population)
print("Fitness Values:")
print(fitness_vals)

# Selection
def selection(population, fitness_vals):
    # Normalize probabilities
    probs = fitness_vals - fitness_vals.min() + 1  # Shift to ensure positivity
    probs = probs / probs.sum()
    N = len(population)
    indices = np.arange(N)
    # Select population based on probabilities
    selected_indices = np.random.choice(indices, size=N, p=probs)
    selected_population = population[selected_indices]
    return selected_population

selected_population = selection(initial_population, fitness_vals)
print("Selected Population:")
print(selected_population)

# Crossover
def crossover(parent1, parent2, pc):
    r = np.random.random()
    if r < pc:
        m = np.random.randint(1, 8)  # Split point
        child1 = np.concatenate((parent1[:m], parent2[m:]))
        child2 = np.concatenate((parent2[:m], parent1[m:]))
    else:
        child1 = parent1.copy()
        child2 = parent2.copy()
    return child1, child2

parent1 = selected_population[0]
parent2 = selected_population[1]
child1, child2 = crossover(parent1, parent2, pc=0.70)
print("Crossover Results:")
print(parent1, "-->", child1)
print(parent2, "-->", child2)

# Mutation
def mutation(child, pm):
    r = np.random.random()
    if r < pm:
        m = np.random.randint(8)  # Random index to mutate
        child[m] = np.random.randint(8)  # Random value for mutation
    return child

# Combined Crossover and Mutation
def crossover_mutation(population, pc, pm):
    N = len(population)
    new_pop = np.empty((N, 8), dtype=int)
    for i in range(0, N, 2):
        parent1 = population[i]
        parent2 = population[(i + 1) % N]  # Wrap around for odd populations
        child1, child2 = crossover(parent1, parent2, pc)
        new_pop[i] = mutation(child1, pm)
        if i + 1 < N:
            new_pop[i + 1] = mutation(child2, pm)
    return new_pop

# Generate a new population
new_population = crossover_mutation(selected_population, pc=0.70, pm=0.10)
print("New Population:")
print(new_population)


Initial Population:
[[1 7 0 0 3 2 2 4]
 [7 0 1 4 7 6 2 4]
 [5 7 2 5 5 1 5 5]
 [1 4 3 4 4 5 0 3]]
Fitness Values:
[-14 -16 -22 -20]
Selected Population:
[[1 4 3 4 4 5 0 3]
 [1 7 0 0 3 2 2 4]
 [1 7 0 0 3 2 2 4]
 [1 4 3 4 4 5 0 3]]
Crossover Results:
[1 4 3 4 4 5 0 3] --> [1 4 3 4 3 2 2 4]
[1 7 0 0 3 2 2 4] --> [1 7 0 0 4 5 0 3]
New Population:
[[1 4 3 4 4 5 0 3]
 [1 7 0 0 3 2 2 4]
 [1 4 3 4 1 5 0 3]
 [1 7 0 0 3 2 2 4]]
